export const ADD_PRODUCT_SUCCESS = `ADD_PRODUCT_SUCCESS`;
export const ADD_PRODUCT_FAILED = `ADD_PRODUCT_FAILED`;

//Categories
export const GET_CATEGORIES_SENT = `GET_CATEGORIES_SENT`;
export const GET_CATEGORIES_SUCCESS = `GET_CATEGORIES_SUCCESS`;
export const GET_CATEGORIES_FAILED = `GET_CATEGORIES_FAILED`;
