//Products actions
export const ADD_PRODUCT_SENT = `ADD_PRODUCT_SENT`;
export const ADD_PRODUCT_SUCCESS = `ADD_PRODUCT_SUCCESS`;
export const ADD_PRODUCT_FAILED = `ADD_PRODUCT_FAILED`;

export const UPDATE_PRODUCT_SENT = `UPDATE_PRODUCT_SENT`;
export const UPDATE_PRODUCT_SUCCESS = `UPDATE_PRODUCT_SUCCESS`;
export const UPDATE_PRODUCT_FAILED = `UPDATE_PRODUCT_FAILED`;

export const DELETE_PRODUCT_SENT = `DELETE_PRODUCT_SENT`;
export const DELETE_PRODUCT_SUCCESS = `DELETE_PRODUCT_SUCCESS`;
export const DELETE_PRODUCT_FAILED = `DELETE_PRODUCT_FAILED`;

export const GET_PRODUCT_SUCCESS = `GET_PRODUCT_SUCCESS`;

// Review
export const ADD_REVIEW_SENT = `ADD_REVIEW_SENT`;
export const ADD_REVIEW_SUCCESS = `ADD_REVIEW_SUCCESS`;
export const ADD_REVIEW_FAILED = `ADD_REVIEW_FAILED`;

//Categories
export const GET_CATEGORIES_SENT = `GET_CATEGORIES_SENT`;
export const GET_CATEGORIES_SUCCESS = `GET_CATEGORIES_SUCCESS`;
export const GET_CATEGORIES_FAILED = `GET_CATEGORIES_FAILED`;

export const ADD_CATEGORY_SENT = 'ADD_CATEGORY_SENT';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILED = 'ADD_CATEGORY_FAILED';

export const DELETE_CATEGORY_SENT = 'DELETE_CATEGORY_SENT';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED';

//Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Analytics
export const GET_ANALYTICS_SENT = 'GET_ANALYTICS_SENT';
export const GET_ANALYTICS_SUCCESS = 'GET_ANALYTICS_SUCCESS';
export const GET_ANALYTICS_FAILED = 'GET_ANALYTICS_FAILED';