//Products actions
export const ADD_PRODUCT_SENT = 'ADD_PRODUCT_SENT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';

export const UPDATE_PRODUCT_SENT = 'UPDATE_PRODUCT_SENT';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED';

export const DELETE_PRODUCT_SENT = 'DELETE_PRODUCT_SENT';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED';

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';

// Review
export const ADD_REVIEW_SENT = 'ADD_REVIEW_SENT';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAILED = 'ADD_REVIEW_FAILED';

//Categories
export const GET_CATEGORIES_SENT = 'GET_CATEGORIES_SENT';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';

//Orders
export const GET_ORDERS_SENT = `GET_ORDERS_SENT`;
export const GET_ORDERS_SUCCESS = `GET_ORDERS_SUCCESS`;
export const GET_ORDERS_FAILED = `GET_ORDERS_FAILED`;

//Recomendation
export const GET_RECOMENDATION_SENT = `GET_RECOMENDATION_SENT`;
export const GET_RECOMENDATION_SUCCESS = `GET_RECOMENDATION_SUCCESS`;
export const GET_RECOMENDATION_FAILED = `GET_RECOMENDATION_FAILED`;
export const ADD_CATEGORY_SENT = 'ADD_CATEGORY_SENT';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILED = 'ADD_CATEGORY_FAILED';

export const DELETE_CATEGORY_SENT = 'DELETE_CATEGORY_SENT';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED';

//Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILED = 'ADD_TO_CART_FAILED';

export const GET_CART_PRODUCTS = 'GET_CART_PRODUCTS';
export const GET_CART_PRODUCTS_SUCCESS = 'GET_CART_PRODUCTS_SUCCESS';
export const GET_CART_PRODUCTS_FAILED = 'GET_CART_PRODUCTS_FAILED';

export const CHANGE_PRODUCT_QTY = 'CHANGE_PRODUCT_QTY';
export const CHANGE_PRODUCT_QTY_FAILED = 'CHANGE_PRODUCT_QTY_FAILED';

export const REMOVE_PRODUCT_FROM_CART_FAILED = 'REMOVE_PRODUCT_FROM_CART_FAILED';

export const SAVE_FOR_LATER = 'SAVE_FOR_LATER';
export const SAVE_FOR_LATER_FAILED = 'SAVE_FOR_LATER_FAILED';

export const GET_SAVED_PRODUCTS = 'GET_SAVED_PRODUCTS';
export const GET_SAVED_PRODUCTS_FAILED = 'GET_SAVED_PRODUCTS_FAILED';
export const GET_SAVED_PRODUCTS_SUCCESS = 'GET_SAVED_PRODUCTS_SUCCESS';

export const MOVE_TO_CART = 'MOVE_TO_CART';
export const MOVE_TO_CART_FAILED = 'MOVE_TO_CART_FAILED';

export const REMOVE_SAVED_PRODUCT = 'REMOVE_SAVED_PRODUCT';
export const REMOVE_SAVED_PRODUCT_FAILED = 'REMOVE_SAVED_PRODUCT_FAILED';

export const APPLY_GIFT_CHARGE_FAILED = 'APPLY_GIFT_CHARGE_FAILED';
// Analytics
export const GET_ANALYTICS_SENT = 'GET_ANALYTICS_SENT';
export const GET_ANALYTICS_SUCCESS = 'GET_ANALYTICS_SUCCESS';
export const GET_ANALYTICS_FAILED = 'GET_ANALYTICS_FAILED';
